name: Run Test

on: [push, pull_request]

permissions:
    contents: read
    packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Check linting
        run: flake8 .
      - name: Run tests
        run: pytest